[project]
name = "pymapgis"
version = "0.1.0"
description = "Modern GIS toolkit"
authors = [
    {name = "Nicholas Karlson",email = "nicholaskarlson@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "geopandas (>=1.1.0,<2.0.0)",
    "fsspec (>=2025.5.1,<2026.0.0)",
    "leafmap (>=0.47.2,<0.48.0)",
    "pydantic-settings (>=2.9.1,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pytest-cov = "^6.1.1"
ruff = "^0.11.13"
black = "^25.1.0"
mypy = "^1.16.0"
pre-commit = "^4.2.0"

