# pyproject.toml  (top of file)

[tool.poetry]              # ← change this line
name = "pymapgis"
version = "0.1.0"
description = "Modern GIS toolkit"
authors = ["Nicholas Karlson <nicholaskarlson@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "pymapgis" }]   # ← tells Poetry to install your code



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pytest-cov = "^6.1.1"
ruff = "^0.11.13"
black = "^25.1.0"
mypy = "^1.16.0"
pre-commit = "^4.2.0"

